import assert from 'node:assert/strict';
import { build } from 'esbuild';
const bundle = await build({stdin: {contents: 'export * from "./src/category-store.ts"; export {readSidecar} from "./src/model.ts";', resolveDir: process.cwd()}, bundle: true, write: false, format: 'esm', platform: 'node'});
const {CategoryStore, defaultCategories, readCategorySettings, validateCategories, readSidecar} = await import(`data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].text).toString('base64')}`);
assert.deepEqual(readCategorySettings(null).map(x => x.label), ['Claim', 'Evidence', 'Method', 'Concept', 'Limitation', 'Note']);
for (const bad of [[], [{id:'constructor', label:'Bad', color:'red', hex:'#ffffff', icon:'tag'}], [...defaultCategories(), {...defaultCategories()[0]}], defaultCategories().map(x=>({...x,archived:true}))]) assert.throws(()=>validateCategories(bad));
assert.throws(()=>validateCategories(defaultCategories().map(x=>({...x,label:'Same'}))), /different name/);
assert.throws(()=>readCategorySettings({categories:'bad'}));
assert.equal(readCategorySettings({}).length,6);
let saved; let notifications = 0;
const store = new CategoryStore(defaultCategories(), async items => { saved = structuredClone(items); });
const unsubscribe = store.subscribe(()=>notifications++);
const custom = {id:'custom-research', label:'Hypothesis', color:'#112233', hex:'#112233', icon:'lightbulb'};
await store.save([...store.all(),custom],0);
assert.equal(notifications,1); assert.equal(store.active().length,7);
assert.equal(new CategoryStore(readCategorySettings({categories:saved})).style(custom.id).label,'Hypothesis');
const raw={version:2,notes:'Keep notes',annotations:[{id:'custom-comment',page:1,category:custom.id,categoryStyle:custom,color:custom.hex,quads:[{x:1,y:2,w:3,h:4}],text:'Quote',comment:'Keep comment',createdAt:1,updatedAt:2}]};
const parsed=readSidecar(JSON.stringify(raw),'paper.pdf');
assert.equal(parsed.annotations[0].category,custom.id);
assert.equal(new CategoryStore().forAnnotation(parsed.annotations[0]).label,'Hypothesis', 'Snapshot survives missing plugin settings');
const changed=store.all(); changed.find(x=>x.id===custom.id).label='Working hypothesis';
await store.save(changed,1);
assert.equal(store.forAnnotation(parsed.annotations[0]).label,'Working hypothesis');
const removed=store.all(); removed.find(x=>x.id===custom.id).archived=true; removed.find(x=>x.id==='note').archived=true;
await store.save(removed,2);
assert.ok(!store.active().some(x=>x.id===custom.id));
assert.equal(store.forAnnotation(parsed.annotations[0]).label,'Working hypothesis');
assert.equal(store.choices(parsed.annotations[0]).at(-1).label,'Working hypothesis (deleted)');
assert.equal(store.preferred(),'claim');
assert.equal(parsed.annotations[0].comment,'Keep comment');
unsubscribe();
await assert.rejects(store.save(store.all(),0),/another window/);
const failed=new CategoryStore(defaultCategories(),async()=>{throw new Error('Disk full');});
await assert.rejects(failed.save([...failed.all(),custom],0),/Disk full/);
assert.equal(failed.active().length,6); assert.equal(failed.revision,0);
let finish;
const concurrent=new CategoryStore(defaultCategories(),()=>new Promise(resolve=>{finish=resolve;}));
const first=concurrent.save([...concurrent.all(),custom],0);
await assert.rejects(concurrent.save(concurrent.all(),0),/another window/);
finish(); await first;
const snapshot=readSidecar(JSON.stringify(parsed),'paper.pdf');assert.deepEqual(snapshot,parsed);
console.log('PASS: custom category validation, persistence, deletion without data loss, snapshot recovery, stale dialogs and failed saves');
